[editor]
scroll-offset = 0
indent-width = 2

[editor.font]
size = 16
family = "monospace"

[ui.font]
size = 13
family = "sans-serif"

[[layout.tab]]
pane = "terminal"

[[layout.tab]]
pane = "split"
axis = "vertical"
percent = [0.2]
active = 1
children = [
  { pane = "file-tree" },
  { pane = "editor" },
]

[[layout.tab]]
pane = "terminal"
